language: java

jdk:
  - oraclejdk8

env:
  - GWT_VERSION=2.7.0
  - GWT_VERSION=2.8.1

after_success:
  - ci/deploy-snapshot.sh

notifications:
  email: false

sudo: false
cache:
  directories:
    - $HOME/.m2
